@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "graphRestriction": {
    "classPackageIncludeFilter": "model", // Solo incluir clases del paquete model
    "classPackageExcludeFilter": "", // No excluir nada más
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "details": {
    "aggregation": "GroupByClass",
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "model.Dentista"
}
diagram meta data end '/

digraph g {
    rankdir="TB"
    splines=polyline

'nodes
subgraph cluster_104069929 {
    label=model
 labeljust=l
 fillcolor="#ececec"
 style=filled

   Dentista104069929[
 label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Dentista</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   edad: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   especialidad: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fechaNacimiento: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   idDentista: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nColegiado: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tratamientosDentista: List&lt;Tratamiento&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ mostrarNombre(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ setIdDentista(idDentista: int): int</TD></TR>
</TABLE>>
 style=filled
 margin=0
 shape=plaintext
 fillcolor="#FFFFFF"
];

Paciente104069929[
 label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Paciente</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   alergias: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   edad: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fechaNacimiento: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   idPaciente: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tratamientosPaciente: List&lt;TratamientoPaciente&gt; [0..*]</TD></TR>
</TABLE>>
 style=filled
 margin=0
 shape=plaintext
 fillcolor="#FFFFFF"
];

Persona104069929[
 label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Persona</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dni: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telefono: int [1]</TD></TR>
</TABLE>>
 style=filled
 margin=0
 shape=plaintext
 fillcolor="#FFFFFF"
];

Tratamiento104069929[
 label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Tratamiento</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dentista: Dentista [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   descripcion: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   idDentista: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   idTratamiento: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   precio: double [1]</TD></TR>
</TABLE>>
 style=filled
 margin=0
 shape=plaintext
 fillcolor="#FFFFFF"
];

TratamientoPaciente104069929[
 label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TratamientoPaciente</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   detalles: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fechaTratamiento: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   idPaciente: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   idTratamiento: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pacienteNombre: String [0..1]</TD></TR>
</TABLE>>
 style=filled
 margin=0
 shape=plaintext
 fillcolor="#FFFFFF"
];
}

'edges
Dentista104069929 -> Tratamiento104069929[label="tratamientosDentista
[0..*]"];
Paciente104069929 -> TratamientoPaciente104069929[label="tratamientosPaciente
[0..*]"];
Persona104069929 -> Dentista104069929[arrowhead=none, arrowtail=empty, dir=both];
Persona104069929 -> Paciente104069929[arrowhead=none, arrowtail=empty, dir=both];
Tratamiento104069929 -> Dentista104069929[label="dentista
[0..1]"];

}
@enduml